### ISSUE TITLE
AttributeError: module 'tensorflow.python.ops.rnn_cell_impl' has no attribute '_like_rnncell'

### ISSUE THREAD

**Issue by cy-dream** [Walleclipse/AGPC#2]
WARNING:tensorflow:From C:\Users\cydream\Desktop\AGPC-master\model\cell.py:12: BasicLSTMCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is deprecated, please use tf.nn.rnn_cell.LSTMCell, which supports all the feature this cell currently has. Please replace the existing code with tf.nn.rnn_cell.LSTMCell(name='basic_lstm_cell').
Traceback (most recent call last):
  File "train_PCGN.py", line 174, in <module>
    main(config)
  File "train_PCGN.py", line 79, in main
    l2_regularize=l2_regularize, learning_rate=learning_rate, max_to_keep=max_checkpoints, max_gradient_norm=max_gradient_norm,
  File "C:\Users\cydream\Desktop\AGPC-master\model\PCGN_model.py", line 89, in __init__
    self.build_model()
  File "C:\Users\cydream\Desktop\AGPC-master\model\PCGN_model.py", line 300, in build_model
    name='PCGNWrapper')
  File "C:\Users\cydream\Desktop\AGPC-master\model\PCGN_attention.py", line 152, in __init__
    if not rnn_cell_impl._like_rnncell(cell):  # pylint: disable=protected-access
AttributeError: module 'tensorflow.python.ops.rnn_cell_impl' has no attribute '_like_rnncell'

我装的tensorflow1.4 出现了这个错误

**Comment by Walleclipse** [comment]
你好， 不好意思 python 3.6 可能会报错。
我用 python 3.5 和 tensorflow-gpu==1.4 验证过了，可以正常运行。
你可能需要装 python 3.5 和  tensorflow-gpu 1.4。

**Comment by ethan-phu** [comment]
你好我也遇到这个问题了！为何会在3.6中报错呢？

**Comment by cookie54sun** [comment]
是因为tf版本问题还是python版本问题？tf 1.15也爆同样的错

**Comment by Walleclipse** [comment]
不好意思，具体原因我也不清楚。
但是只有在python 3.5 和 tensorflow-gpu==1.4 同时满足时下才可以正常运行。
这个代码比较老了，和新的python库不太兼容，但是在新的tensorflowPython版本里实现该代码的功能反而会更容易一点。

**Comment by xzhws** [comment]
不需要更改Python的版本，可以参考这种解决方式：[https://github.com/sjvasquez/handwriting-synthesis/issues/22#issuecomment-506931520](https://github.com/sjvasquez/handwriting-synthesis/issues/22#issuecomment-506931520)
